### ISSUE TITLE
[BUG] Materialized views not showing up

### ISSUE THREAD

**Issue by keur** [newrelic/nri-postgresql#39]
##### Description of the problem

The query in `buildSchemaListForDatabase` does not include materialized views, but monitoring stats for materialized views can be found in `pg_statio_user_tables`.

##### OS

- [x] All of them
- [ ] Amazon Linux, all versions
- [ ] CentOS, version 6 or higher
- [ ] Debian, version 7 ("Wheezy") or higher
- [ ] Red Hat Enterprise Linux (RHEL), version 6 or higher
- [ ] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
- [ ] Windows Server, 2008 and 2012 and their service packs

**Comment by keur** [comment]
It pulls the table information from `information_schema.tables`, and this post from the mailing list explains why it doesn't show up there 

https://www.postgresql.org/message-id/3794.1412980686%40sss.pgh.pa.us

**Comment by Tylerlhess** [comment]
This issue is actually not just materialized views but any database that is not the original database connected to. When the collection list is built in line 77 in buildCollectionListFromDatabaseNames. It includes dbnames and builds a list out of this string. It then loops through those names. The query that is now part of buildSchemaListForDatabase was part of the db looping in the original commit of src/collections/collections.go. It still is looping over each database in the buildCollectionListFromDatabaseNames but it is seemingly not switching databases and is running the query only against the primary database. You will still get some tables back for each database as the statistics tables (all that I am seeing come back) have the same names and schemas. It seems that the other schemas are not being pulled correctly but the databases are being seen and connected to as the tables that do get looked up have correct information.
 I wish I was better at Go so I could just do the PR myself but this is where the issue is.

**Comment by camdencheek** [comment]
Hi @Tylerlhess -- thanks for the detailed info. I'll see what I can do 👍

**Comment by Tylerlhess** [comment]
the issue might be that is it not pulling the public schema. It seems that that is the standard among the databases in my cluster and the one outlier has table data coming through for their tables.

**Comment by davidgit** [comment]
We appreciate you taking the time to bring this to our attention. After reviewing this issue, we are unable to commit on a timeline to resolution for more than a year. When committing to resolve an issue, we take into account the type of issue, the customer impact, and the development effort required. If the situation changes, we will revisit this decision.
