### ISSUE TITLE
Execute Custom Metrics Query independent of metrics to allow running it at a different interval

### ISSUE THREAD

**Issue by adiosspandit** [newrelic/nri-postgresql#62]
Custom Metric Query is too costly to run at the same polling interval as other metrics

## Feature Description
I would like to fetch custom metrics query at a different polling interval than standard metrics

## Describe Alternatives
Looked into setting a separate configuration file to just execute custom query. But from the code it looks like Custom Metrics Query is run only when Metrics are present and always run as part of collecting all metrics

## Additional context
Customer runs a complex query to fetch some custom metrics which is quite costly to be running at the same interval as other metrics

## Priority
Must Have

**Comment by roobre** [comment]
Hi,

Unfortunately, and given the architecture of the integrations, this is technically very dificult to achieve at the moment, since the integrations run in a one-shot and essentially stateless mode.

We'll note this limitation internally and try to work towards removing this limitation in the future.
