### ISSUE TITLE
Integer out of range prevents metrics from being sent

### ISSUE THREAD

**Issue by moodgorning** [newrelic/nri-postgresql#69]
We are erunning into issues where values in the pg_stat_* tables that are too big give errors like:

## Description
if some of the counter values in the stat tables exceed integer limts the metrics stop being sent

'`Jun 25 03:50:17 ip-172-31-35-173 newrelic-infra-service[14552]: time="2021-06-25T03:50:17Z" level=debug msg="Integration command wrote to stderr." instance=postgres integration=com.newrelic.postgresql prefix=config/postgresql stderr="[ERR] Could not execute instance query: sql: Scan error on column index 6, name \"buffers_allocated\": converting driver.Value type int64 (\"15855543149\") to a int: value out of range\n[ERR] Could not execute database query: sql: Scan error on column index 5, name \"block_reads\": converting driver.Value type int64 (\"16289158795\") to a int: value out of range\n[ERR] Could not execute database query: sql: Scan error on column index 2, name \"temporary_bytes_written\": converting driver.Value type int64 (\"45811045239996\") to a int: value out of range\n" working-dir=/var/db/newrelic-infra/newrelic-integrations`

This can be temporarily fixed by running commands like

'SELECT  pg_stat_reset();
SELECT pg_stat_reset_shared('bgwriter')'

but enabling the collector to handle this would be better to not get surprised by metrics dropping all of sudden

## Expected Behavior
I would expect the collector to be able to handle all postgres data types

## Steps to Reproduce
Updat the stats table to a value such as 45811045239996

**Comment by alvarocabanas** [comment]
Hello @moodgorning I have been investigating this issue and I could see that it's caused because of the following behaviour:

In the integration the values got from  Postgresql are unmarshaled to **int.** In Go, **int** is automatically set as 32 or 64 bit depending on the architecture the system is running on. The numbers you provide on your log trace are greater than 32 bits. The SQL library automatically sets those numbers as **int64** by reflection because it detects their length. When they are unmarshaled to **int** on the system you are running the integration, int is 32 bits and gets out of range.

This can be solved by modifying the code to always unmarshal to int64, because on 32 bit systems it will continue working 
 as expected because GO automatically handles this by using two blocks of 32 bits. 

Right now we don't support 32 bit architecture for most OSS, so I would like to know which operating system and architecture are you running this agent and integration to get the most information as possible.
